### PR TITLE
terminal screen

### PR DESCRIPTION
**Pull request by adeebshihadeh**

### CODE REVIEW

**Comment by arthurwolf** [comment]
ooooooh, nice :)

**Comment by ghost** [comment]
Remember to cleanup that terminal output,  we had some slow browser issues
with ours,  i now keep it limited to last 300 lines
https://github.com/openhardwarecoza/LaserWeb3/blob/master/public/js/main.js#L480-482

**Comment by ghost** [comment]
Maybe also make the append a function,  so you can print to the terminal
log from other screens.  Helps with user troubleshooting

**Comment by adeebshihadeh** [comment]
yeah I realized I was only getting responses from other screens after I made the PR. @arthurwolf merged it right as I was about to push a fix

**Comment by ghost** [comment]
That parts a good thing.  Keep the other responses.   As i said,  seeing a
full log nakes troubleshooting easier.  Just cut it at a 300 line limit
like i do in LaserWeb.  Well proven,  works.

**Pull request merged**
