### PR TITLE
Definitions file

### PR DESCRIPTION
**Pull request by funinthefalls**
Not sure if I created this pull request properly, let me know if I need to change anything. But the definitions are complete (For the most part.) If you see "???????????????????" it is because I either did not know what it meant, or could not come up with an easy explanation.

### CODE REVIEW

**Comment by arthurwolf** [comment]
Hey.

Thank you so much !
You are merging gh-pages into master. I think you want to be merging gh-pages into gh-pages

Tell me if you need any help with that.
Cheers.

**Comment by funinthefalls** [comment]
OK will try that.

**Comment by funinthefalls** [comment]
Will not let me do gh-pages to gh-pages :(

**Comment by arthurwolf** [comment]
Well that's weird ... looking into it.

**Comment by arthurwolf** [comment]
Done ! https://github.com/arthurwolf/fabrica/pull/5

Thank you so much !

**Comment by arthurwolf** [comment]
This is incredible work. I'm having computer problems right now, but as soon as I figure those out, I'll be integrating this into fabrica !

**Pull request closed without merging**
